engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - src/**/*.js
  - test/**/*.js
exclude_paths:
- dist/**/*
- public/build/**/*
- public/external/**/*
